/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ylq17_myapplication_NdkTest */

#ifndef _Included_com_example_ylq17_myapplication_NdkTest
#define _Included_com_example_ylq17_myapplication_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ylq17_myapplication_NdkTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ylq17_myapplication_NdkTest_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
